### ISSUE TITLE
crashes when clicking on it

### ISSUE THREAD

**Issue by bentxt** [sanette/randomize#2] opened 2022-03-11 09:00 UTC
Hi,
The app crashes when randomly clickon it, with the error:

./randomize                                                                                                                                -- INSERT --
Loading Bogue 20220115 with config dir /Users/bkb/.opam/default/share/bogue/themes/default
2022-03-11 09:58:52.732 randomize[15951:19657024] INFO: Using SDL 2.0.20
Fatal error: exception Invalid_argument("Empty chain has not depth")

**Comment by sanette** [comment] 2022-03-11 10:23
could you try with the latest bogue version from github?

**Comment by sanette** [comment] 2022-03-11 12:35
I cannot reproduce this bug with bogue.20220115 from opam
did you install with opam ?

but I know that this "Empty chain has not depth" error appeared with some recent changes to the Chain module
(after the opam release iirc). In principle this has been corrected some time ago, and the latest version (20220307) should work.

**Comment by sanette** [comment] 2024-02-04 10:07
Closing this. Feel free to reopen if the problem persists

**Closed as completed by sanette** 2024-02-04 10:07 UTC
